// <auto-generated />
namespace SmallJob.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createassigndjob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createassigndjob));
        
        string IMigrationMetadata.Id
        {
            get { return "201812051634024_create assignd job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
